### PR TITLE
Ron/kafkacluster/prometheus

### PR DESCRIPTION
**Pull request by josuerole**
## Checklist

- [x] I've followed the [Contributing guidelines](https://github.com/community-health-demo/.github/blob/main/CONTRIBUTING.md)
- [x] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [] I've linked an open issue
- [x] I've added tests that fail without this PR but pass with it
- [x] I've linted and tested my code
- [x] I've updated documentation (if appropriate)

### CODE REVIEW

**Review by AllisonScott97 — APPROVED** [review]
Amazing job setting up the Kafka cluster and Prometheus!

**Review by JustinTzHLin — APPROVED** [review]
Go Go Clusters

**Review by julesdmai — APPROVED** [review]
Great work setting up the demo Kafka cluster Ron!

**Review by MattKonop — APPROVED** [review]
Great job Ron! Adding a Kafka Cluster with prometheus is super helpful

**Pull request merged**
