### PR TITLE
feat: Jules/backend

### PR DESCRIPTION
**Pull request by julesdmai**
## Description

This pull request implements containerizing the frontend, starting the metrics collection framework, and introducing routes for managing favorites. 

## Checklist

- [X] I've followed the [Contributing guidelines](https://github.com/community-health-demo/.github/blob/main/CONTRIBUTING.md)
- [X] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [ ] I've linked an open issue
- [ ] I've added tests that fail without this PR but pass with it
- [X] I've linted and tested my code
- [X] I've updated documentation (if appropriate)

### CODE REVIEW

**Review by JustinTzHLin — APPROVED** [review]
All-stars team!

**Review by josuerole — APPROVED** [review]
Great Job Jules!

**Review by MattKonop — APPROVED** [review]
Excited to see that the front end is containerized!

**Review by AllisonScott97 — APPROVED** [review]
Looks good, thank you for adding comments as always and the middleware for favorites is very cool.

**Pull request merged**
