### PR TITLE
Matt docker 2

### PR DESCRIPTION
**Pull request by MattKonop**
## Description
Updated Kafka Kluster docker container to fit Mac. Updated some UI elements. This is the stable version for MVP.

## Checklist

- [x] I've followed the [Contributing guidelines](https://github.com/community-health-demo/.github/blob/main/CONTRIBUTING.md)
- [x] I've titled my PR according to the [Conventional Commits spec](https://conventionalcommits.org)
- [ ] I've linked an open issue
- [ ] I've added tests that fail without this PR but pass with it
- [x] I've linted and tested my code
- [x] I've updated documentation (if appropriate)

### CODE REVIEW

**Review by julesdmai — APPROVED** [review]
Thanks for the bug fixes. Great job team on reaching MVP!

**Review by josuerole — APPROVED** [review]
Great Job! Our MVP is ready!

**Review by JustinTzHLin — APPROVED** [review]
Again, All-Stars Team

**Review by AllisonScott97 — COMMENTED** [review]
Amazing job getting us to MVP + fixing the signup bug.

**Pull request merged**
